name: C/C++ CI

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install python3-setuptools
      - run: pip3 install git+https://github.com/icpc-jag/rime
      - run: rime test
