name: C/C++ CI
on: [push]

jobs:
  build:
    name: run rime test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip install git+https://github.com/icpc-jag/rime
    - name: Run tests for player1
      run: rime test player1
      if: contains(github.ref, 'tags/player1')
